[package]
name = "helloERC20" # the name of the package
version = "0.1.0"    # the current version, obeying semver

[dependencies]
starknet = ">=2.0.0-rc0"
[lib]
sierra = true  # Enable Sierra codegen.
casm = false   # Enable CASM codegen.

[[target.starknet-contract]]
allowed-libfuncs = true
